In [1]:
import torch

In [6]:
t1 = torch.tensor(4.)
print(t1.shape)  # torch.Size([])
print(t1)
print(t1.dtype)

torch.Size([])
tensor(4.)
torch.float32


In [7]:
t1.dtype

torch.float32

In [10]:
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [11]:
print(t2.shape)
print(t2.dtype)

torch.Size([4])
torch.float32


In [12]:
t22 = torch.tensor([3])
print(t22)
print(t22.shape)
print(t22.dtype)

tensor([3])
torch.Size([1])
torch.int64


In [13]:
t3 = torch.tensor([[5., 6],
                   [7, 8],
                   [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [14]:
t4 = torch.tensor([
    [[11, 12, 13],
     [13, 14, 15]],
    [[15, 16, 17],
     [17, 18, 10]]])
t4

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [17, 18, 10]]])

In [15]:
print(t4.dtype)
print(t4.shape)

torch.int64
torch.Size([2, 2, 3])


In [16]:
### Tensor operations and gradients
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [23]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [26]:
y.backward()  # to calculate the derivatives

In [27]:
print("dy/dx:", x.grad)  # x.grad stands for the gradient.
print("dy/dw:", w.grad)
print("dy/db:", b.grad)

dy/dx: None
dy/dw: tensor(6.)
dy/db: tensor(2.)


In [28]:
# interoperatbility with Numpy
import numpy as np

x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [29]:
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [30]:
print(y.dtype)
print(y.shape)

torch.float64
torch.Size([2, 2])


In [31]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [32]:
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

In [33]:
print(type(z))
print(z.shape)

<class 'numpy.ndarray'>
(2, 2)
